### ISSUE TITLE
Should Not Default New Chrome Window to Extension

### ISSUE THREAD

**Issue by rashid-sial** [topcoderinc/tc-chrome-extension#5]
1. I installed the app.
2. I opened a new tab.
3. The extension would open in every new tab I loaded.
4. Then I saw this was done by default:
   ![image](https://cloud.githubusercontent.com/assets/5807576/7241016/bf7c1440-e783-11e4-9361-c7b263a1c2df.png)

**Comment by jeffdonthemic** [comment]
I agree with you on this. I've remove the override for the new tab. I'll update it shortly.
