### ISSUE TITLE
Same version as last one 0.2

### ISSUE THREAD

**Issue by kbowerma** [topcoderinc/tc-chrome-extension#7]
![screen shot 2015-04-23 at 4 26 14 pm](https://cloud.githubusercontent.com/assets/1180747/7307897/7f22b4e0-e9d5-11e4-8788-6826de37714b.png)

**Comment by jeffdonthemic** [comment]
Yeah.... I think yo were the only person that installed the old version and I forgot. So I didn't upgrade the version number. You should probably delete the extension you have now and download the latest one.
